# [conda]
# disabled = true

# [git_status]
# disabled = true
# conflicted = "ğŸ³ "
# ahead = "ğŸ’¨ "
# behind = "ğŸ˜° "
# diverged = "ğŸ˜µ "
# untracked = "ğŸ¤·â€ "
# stashed = "ğŸ“¦ "
# modified = "ğŸ“ "
# staged.value = "ğŸ”° "
# staged_count.enabled = true
# staged_count.style = "green"
# renamed = "ğŸ‘… "
# deleted = "ğŸ—‘ "
# show_sync_count = true
# prefix = ""
# suffix = " "

# [time]
# disabled = false
# format = "%l:%M:%S%P"
# use_12hr = true
# utc_time_offset = -5
