# [conda]
# disabled = true

# [git_status]
# disabled = true
# conflicted = "ğŸ³ "
# ahead = "ğŸ’¨ "
# behind = "ğŸ˜° "
# diverged = "ğŸ˜µ "
# untracked = "ğŸ¤·â€ "
# stashed = "ğŸ“¦ "
# modified = "ğŸ“ "
# staged.value = "ğŸ”° "
# staged_count.enabled = true
# staged_count.style = "green"
# renamed = "ğŸ‘… "
# deleted = "ğŸ—‘ "
# show_sync_count = true
# prefix = ""
# suffix = " "

# [time]
disabled = false
format = "%l:%M:%S%P"
use_12hr = true
utc_time_offset = -5

# dracula theme
[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[Î»](bold #ff5555)"
success_symbol = "[Î»](bold #f8f8f2)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
